# CMSC 197: Quiz 1
### LESTER D. PIORQUE BSCS IV



# Part 1

In [10]:
%pylab inline

%pylab is deprecated, use %matplotlib inline and import the required libraries.
Populating the interactive namespace from numpy and matplotlib


#### Creating y_hat and y arrays

In [11]:
y_hat = np.linspace(-1, 1, 20)   # array for y_hat with starting value, stop, and number of items
#y_hat = y_hat.reshape(4,5)      # reshape turns the 1d array into 2d array 
y_hat

array([-1.        , -0.89473684, -0.78947368, -0.68421053, -0.57894737,
       -0.47368421, -0.36842105, -0.26315789, -0.15789474, -0.05263158,
        0.05263158,  0.15789474,  0.26315789,  0.36842105,  0.47368421,
        0.57894737,  0.68421053,  0.78947368,  0.89473684,  1.        ])

In [12]:
y = np.linspace(0, 1, 20)        # array for y with starting value, stop, and number of items
#y = y.reshape(4,5)              # reshape turns the 1d array into 2d array 
y

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

#### Shape and dimension of two arrays

In [13]:
y_hat.shape    # shape of y_hat

(20,)

In [14]:
y_hat.ndim    # dimension which is 1D

1

In [15]:
y.shape        # shape of y

(20,)

In [16]:
y.ndim        # dimension which is 1D

1

#### Function for MEAN SQUARED ERROR (MSE)

In [19]:
def mean_squared_error(y_hat, y):  # function name and parameters

   diff = y_hat - y                # formula in getting the MSE
   diff_squared = diff ** 2
   L = diff_squared.mean()
   
   return L                        # L variable holds the result of the process

print('MEAN SQUARED ERROR =',mean_squared_error(y_hat,y))

MEAN SQUARED ERROR = 0.3421052631578948


#### Function for MEAN ABSOLUTE ERROR (MAE)

In [20]:
def mean_absolute_error(y_hat, y):  # function name and parameters

   diff = y_hat - y                 # formula in getting the MAE
   diff_abs = np.absolute(diff)
   L = diff_abs.mean()
   
   return L                         # L variable holds the result of the process

print('MEAN ABSOLUTE ERROR =',mean_absolute_error(y_hat,y))

MEAN ABSOLUTE ERROR = 0.4999999999999999


#### Function for MEAN SQUARED LOGARITHMIC ERROR (MSLE)

In [25]:
def mean_squared_log_error(y_hat, y):

    if (y_hat > 0).all() or (y > 0).all():   # condition will check for the values
        sum_y_hat = np.log(y_hat+1)          # log 0 will be undefined
        sum_y = np.log(y+1)
        L = np.mean((sum_y_hat - sum_y)**2)

        return L
    
    else:
        raise ValueError("negative numbers")            # raise error if values are negative or zero
      
print('MEAN SQUARED LOGARITHMIC ERROR =',mean_squared_log_error(y_hat,y))       
# this function raised an error because the arrays contain negative numbers

ValueError: negative numbers

#### Function for MEAN ABSOLUTE PERCENTAGE ERROR (MAPE)

In [34]:
def mean_absolute_percentage_error(y_hat, y):
    diff = (y_hat - y)                 # formula for MAPE
    div = (y != 0)
    diff_1 = np.divide(diff, div)
    diff_abs = np.absolute(diff_1)
    sum = diff_abs.mean()
    L = (0.05)*(sum)                  # result of the function
    
    return L

print('MEAN ABSOLUTE PERCENTAGE ERROR =',mean_absolute_percentage_error(y_hat,y))
# this function gave an infinite result because y array has a zero number

MEAN ABSOLUTE PERCENTAGE ERROR = inf


C:\Users\Webb\AppData\Local\Temp\ipykernel_13084\2514504794.py:4: RuntimeWarning: divide by zero encountered in true_divide
  diff_1 = np.divide(diff, div)




# Part 2

#### Creating 1D array M using the arrange function

In [35]:
M = np.arange(1, 17)    # creating an array M
M

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

#### Reshape the 1D array into 2D array

In [36]:
N = M.reshape(4, 4)    # reshaping the array into 2D
N

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

#### Getting the second row of N

In [37]:
N[1]                  # calling the second row of N

array([5, 6, 7, 8])

#### The mininum values and location in each column

In [38]:
N.min(axis = 0)       # min values of each column

array([1, 2, 3, 4])

In [39]:
N.argmin(axis = 0)    # indices of each min values

array([0, 0, 0, 0], dtype=int64)

#### The average of Matrix N

In [40]:
N.mean()              # mean of the whole matrix

8.5

#### Creating vector V with 4 elements

In [41]:
V = np.array([1, 1, 1, 1])  # creating another vector with four elements

#### The dot product of N and V

In [42]:
np.dot(N, V)          # solving for the dot product of matrix N and V

array([10, 26, 42, 58])